export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as ValueProposition } from "./ValueProposition";
export { default as Services } from "./Services";
export { default as Process } from "./Process";
export { default as Pricing } from "./Pricing";
export { default as CTA } from "./CTA";
export { default as Footer } from "./Footer";
export { default as Reveal } from "./Reveal";
